// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Narratum.Persistence;

#nullable disable

namespace Narratum.Persistence.Migrations
{
    [DbContext(typeof(NarrativumDbContext))]
    [Migration("20260719114013_AddStoryWorld")]
    partial class AddStoryWorld
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Narratum.Persistence.PageSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("NarrativeText")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptsSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLlmOutput")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedCharacters")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedChoices")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedPipelineResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedSecrets")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SlotName", "PageIndex")
                        .IsUnique();

                    b.ToTable("PageSnapshots");
                });

            modelBuilder.Entity("Narratum.Persistence.SaveSlotMetadata", b =>
                {
                    b.Property<string>("SlotName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedWorld")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEvents")
                        .HasColumnType("INTEGER");

                    b.HasKey("SlotName");

                    b.ToTable("SaveSlots");
                });

            modelBuilder.Entity("Narratum.Persistence.SaveStateSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SlotName")
                        .IsUnique();

                    b.ToTable("SavedStates");
                });
#pragma warning restore 612, 618
        }
    }
}
